### ISSUE TITLE
the plugin complains about a variable [ignore_batches] that is not found 

### ISSUE THREAD

**Issue by AbdelghaniDr** [eugen0329/vim-esearch#12]
the plugin **used to complain sometimes** ( and i could not reproduce the issue ) about a not found variable `ignore_batches` in `vim-esearch\autoload\esearch\out\win.vim` ( may be in this expression `let ignore_batches = esearch.ignore_batches` ( it's like `esearch.ignore_batches` is not found) which made me add it in my vimrc : 
```
 let esearch = {
      \ 'adapter':        'pt',
      \ 'backend':        'vimproc',
      \ 'out':            'win',
      \ 'batch_size':     1000,
      \ 'use':            ['visual', 'hlsearch', 'last'],
      \ 'ignore_batches': 0  <-- *** HERE ***
      \}
```

and I don't even know if the change I made changed anything in the situation.
well i didn't see the error in a couple a days, but I thought I should mention it.

**Comment by eugen0329** [comment]
I have an idea what is the reason. Will be fixed in a few days.

**Comment by eugen0329** [comment]
I have reproduced the same behavior during development of upcoming vim 8 job control backend. This problem was fixed in 380ef78. So I suppose, the plugin should works fine after update to the latest version.

**Comment by AbdelghaniDr** [comment]
I'm still getting the error, here's a screen shot on windows : 
![esearch](https://cloud.githubusercontent.com/assets/9962871/21026274/311eb6cc-bd8c-11e6-8f2e-d3bc809c322d.png)

and on mac os sierra :
<img width="631" alt="screen shot 2016-12-08 at 21 21 27" src="https://cloud.githubusercontent.com/assets/9962871/21026329/69b73b26-bd8c-11e6-83e2-35becfc4f272.png">

I'm running [this version](https://github.com/eugen0329/vim-esearch/commit/017e59f713c0f97805f6bca2e65e9aef57505263)

**Comment by eugen0329** [comment]
Underlying code is rewritten and ignore_batches option isn't used anymore. Please, update the plugin and reopen if the error persists.
